/*
======================================================================
PROJECT: Northwind Business Analysis
FILE: 05_employee_analysis.sql
DESCRIPTION: Sales Force Performance Assessment and Revenue Contribution.
METHODOLOGY STEP: [A] Exploratory Analysis (Employee Performance)
======================================================================
*/

-- ===================================================================
-- SECTION 1: SALES FORCE LEADERBOARD
-- ===================================================================

-- -------------------------------------------------------------------
-- 1.1. Net Revenue Contribution by Sales Representative
-- Objective: Rank internal employees based on the total net revenue 
--            generated by the orders they managed.
-- Note: Includes employee names directly in the GROUP BY to provide 
--       clear, human-readable data layers for reporting.
-- -------------------------------------------------------------------
SELECT 
    e.EmployeeID,
    e.FirstName,
    e.LastName,
    e.Title AS EmployeeRole,
    SUM(od.Quantity * od.UnitPrice * (1 - od.Discount)) AS TotalRevenueGenerated
FROM dbo.Employees e 
INNER JOIN dbo.Orders o ON e.EmployeeID = o.EmployeeID 
INNER JOIN dbo.[Order Details] od ON o.OrderID = od.OrderID
GROUP BY 
    e.EmployeeID,
    e.FirstName,
    e.LastName,
    e.Title
ORDER BY TotalRevenueGenerated DESC;